### PR TITLE
update EulerOS-2.3.1809 for aarch64 and x86_64

### PR DESCRIPTION
**Pull request by liusdu**

### CODE REVIEW

**Comment by initlove** [comment]
It works for me, but some extra files found, please remove that:
1.  /euleros-x86.tar.xz
2.  /var/lib/yum/yumdb
3. /var/lib/yum/history

**Comment by liusdu** [comment]
@initlove  updated!

**Comment by liusdu** [comment]
@initlove  updated!

**Comment by initlove** [comment]
LGTM

**Pull request merged**
