### PR TITLE
Add support for aarch64 architecture

### PR DESCRIPTION
**Pull request by odidev**
Created Pull request going by the discussion on #10 .

Please have a look and provide your guidance.

Regards,

### CODE REVIEW

**Comment by liangchenye** [comment]
The base image looks good, just two opinions founded:
1.  the packages are a little different with our default setting:
https://github.com/isula/isula-composer/blob/master/config/docker.yml
2.  locale infos should be removed
2.1 ```localedef --list-archive | grep -v -i ^en_US.utf8 | xargs localedef --delete-from-archive```
2.2  remove files under `/usr/share/locale/` except `en_US and zh_CN`

**Comment by liangchenye** [comment]
@odidev I think I need to add these two opinions to this project's README :)

**Comment by odidev** [comment]
Thanks, @liangchenye for taking out your time to review this PR.
Do I need to do anything else for this, or can this be taken at your end now?

Regards,

**Comment by liangchenye** [comment]
@odidev I'll do it.

**Comment by odidev** [comment]
Thanks @liangchenye 

Regards,

**Comment by odidev** [comment]
Thanks, @liangchenye :smile: 

Hope to see ```arm64v8``` in the list of architectures for ```EulerOS``` very soon :crossed_fingers: 

Regards,

**Comment by odidev** [comment]
Hi Guys,
Is there any update w.r.t. work in the direction of support for ARM64?

I would be happy to assist if something is required from my side to get ```EulerOS``` in the official support list of ```arm64v8```

Regards,

**Comment by lag-linaro** [comment]
@liangchenye I too am very interested in AAarch64 (ARM64) support.

How are things progressing?

**Comment by odidev** [comment]
Hi @liangchenye 
Sorry to bother you again and again
But is there any update w.r.t. AARCH64 architecture?

Regards,

**Comment by liangchenye** [comment]
@odidev @lag-linaro sorry, update too late.

@odidev my team member created a smaller image, but I think you contribute more to this PR.
So  I add a PR to your repository.  It works in my test. If you think that is good, please check in that and I'll update this accordingly.

**Pull request merged**
